// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
lv_chart_series_t* ui_Chart1_series_1 ;
lv_chart_series_t* ui_Chart1_series_2 ;



void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 480);
lv_obj_set_height( ui_Panel1, 272);
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Chart1 = lv_chart_create(ui_Screen1);
lv_obj_set_width( ui_Chart1, 319);
lv_obj_set_height( ui_Chart1, 193);
lv_obj_set_x( ui_Chart1, -34 );
lv_obj_set_y( ui_Chart1, -33 );
lv_obj_set_align( ui_Chart1, LV_ALIGN_CENTER );
lv_chart_set_type( ui_Chart1, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_Chart1, 350);
lv_chart_set_range( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 3500);
lv_chart_set_range( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 3500);
lv_chart_set_div_line_count( ui_Chart1, 6, 6);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 0, 5, 0, 2, false, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 5, 3, 5, 2, true, 10);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 5, 0, 2, false, 25);
ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x0516FB), LV_CHART_AXIS_SECONDARY_Y);
static lv_coord_t ui_Chart1_series_1_array[350];
ui_Chart1_series_2 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xD8F707), LV_CHART_AXIS_SECONDARY_Y);
static lv_coord_t ui_Chart1_series_2_array[350];
lv_obj_set_style_bg_color(ui_Chart1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Chart1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_color(ui_Chart1, lv_color_hex(0xDDDDE7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_Chart1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -130 );
lv_obj_set_y( ui_Label1, 79 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"WaveForm(Hz):");

ui_Checkbox1 = lv_checkbox_create(ui_Screen1);
lv_checkbox_set_text(ui_Checkbox1,"50Hz");
lv_obj_set_width( ui_Checkbox1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox1, -199 );
lv_obj_set_y( ui_Checkbox1, 107 );
lv_obj_set_align( ui_Checkbox1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Checkbox2 = lv_checkbox_create(ui_Screen1);
lv_checkbox_set_text(ui_Checkbox2,"500Hz");
lv_obj_set_width( ui_Checkbox2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox2, -126 );
lv_obj_set_y( ui_Checkbox2, 107 );
lv_obj_set_align( ui_Checkbox2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Checkbox3 = lv_checkbox_create(ui_Screen1);
lv_checkbox_set_text(ui_Checkbox3,"1kHz");
lv_obj_set_width( ui_Checkbox3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox3, -59 );
lv_obj_set_y( ui_Checkbox3, 107 );
lv_obj_set_align( ui_Checkbox3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Checkbox4 = lv_checkbox_create(ui_Screen1);
lv_checkbox_set_text(ui_Checkbox4,"on");
lv_obj_set_width( ui_Checkbox4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox4, 151 );
lv_obj_set_y( ui_Checkbox4, 86 );
lv_obj_set_align( ui_Checkbox4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Checkbox5 = lv_checkbox_create(ui_Screen1);
lv_checkbox_set_text(ui_Checkbox5,"off");
lv_obj_set_width( ui_Checkbox5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox5, 206 );
lv_obj_set_y( ui_Checkbox5, 86 );
lv_obj_set_align( ui_Checkbox5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Checkbox6 = lv_checkbox_create(ui_Screen1);
lv_checkbox_set_text(ui_Checkbox6,"100us");
lv_obj_set_width( ui_Checkbox6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox6, 179 );
lv_obj_set_y( ui_Checkbox6, 53 );
lv_obj_set_align( ui_Checkbox6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Checkbox7 = lv_checkbox_create(ui_Screen1);
lv_checkbox_set_text(ui_Checkbox7,"500us");
lv_obj_set_width( ui_Checkbox7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox7, 180 );
lv_obj_set_y( ui_Checkbox7, 25 );
lv_obj_set_align( ui_Checkbox7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Checkbox8 = lv_checkbox_create(ui_Screen1);
lv_checkbox_set_text(ui_Checkbox8,"1ms");
lv_obj_set_width( ui_Checkbox8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox8, 172 );
lv_obj_set_y( ui_Checkbox8, -4 );
lv_obj_set_align( ui_Checkbox8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Checkbox9 = lv_checkbox_create(ui_Screen1);
lv_checkbox_set_text(ui_Checkbox9,"5ms");
lv_obj_set_width( ui_Checkbox9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox9, 174 );
lv_obj_set_y( ui_Checkbox9, -33 );
lv_obj_set_align( ui_Checkbox9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Checkbox10 = lv_checkbox_create(ui_Screen1);
lv_checkbox_set_text(ui_Checkbox10,"10ms");
lv_obj_set_width( ui_Checkbox10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox10, 177 );
lv_obj_set_y( ui_Checkbox10, -60 );
lv_obj_set_align( ui_Checkbox10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox10, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 173 );
lv_obj_set_y( ui_Label3, -85 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"TimeScale:");

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 24 );
lv_obj_set_y( ui_Label4, 82 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"CH1 Vpp:");

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 25 );
lv_obj_set_y( ui_Label5, 108 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"CH2 Vpp:");

ui_Button1 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button1, 71);
lv_obj_set_height( ui_Button1, 30);
lv_obj_set_x( ui_Button1, 174 );
lv_obj_set_y( ui_Button1, -114 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 174 );
lv_obj_set_y( ui_Label6, -114 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"STOP");
lv_label_set_recolor(ui_Label6,"true");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFEFBFB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, 77 );
lv_obj_set_y( ui_Label7, 83 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"     ");

ui_Label8 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, 77 );
lv_obj_set_y( ui_Label8, 109 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"     ");

ui_Checkbox11 = lv_checkbox_create(ui_Screen1);
lv_checkbox_set_text(ui_Checkbox11,"on");
lv_obj_set_width( ui_Checkbox11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox11, 151 );
lv_obj_set_y( ui_Checkbox11, 116 );
lv_obj_set_align( ui_Checkbox11, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox11, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Checkbox12 = lv_checkbox_create(ui_Screen1);
lv_checkbox_set_text(ui_Checkbox12,"off");
lv_obj_set_width( ui_Checkbox12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox12, 206 );
lv_obj_set_y( ui_Checkbox12, 116 );
lv_obj_set_align( ui_Checkbox12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox12, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 106 );
lv_obj_set_y( ui_Label2, 86 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"CH1");

ui_Label9 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, 107 );
lv_obj_set_y( ui_Label9, 117 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"CH2");

lv_obj_add_event_cb(ui_Checkbox1, ui_event_Checkbox1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Checkbox2, ui_event_Checkbox2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Checkbox3, ui_event_Checkbox3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Checkbox4, ui_event_Checkbox4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Checkbox5, ui_event_Checkbox5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Checkbox6, ui_event_Checkbox6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Checkbox7, ui_event_Checkbox7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Checkbox8, ui_event_Checkbox8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Checkbox9, ui_event_Checkbox9, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Checkbox10, ui_event_Checkbox10, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Label7, ui_event_Label7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Label8, ui_event_Label8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Checkbox11, ui_event_Checkbox11, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Checkbox12, ui_event_Checkbox12, LV_EVENT_ALL, NULL);

}
