// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Chart1;
lv_obj_t *ui_Label1;
void ui_event_Checkbox1( lv_event_t * e);
lv_obj_t *ui_Checkbox1;
void ui_event_Checkbox2( lv_event_t * e);
lv_obj_t *ui_Checkbox2;
void ui_event_Checkbox3( lv_event_t * e);
lv_obj_t *ui_Checkbox3;
void ui_event_Checkbox4( lv_event_t * e);
lv_obj_t *ui_Checkbox4;
void ui_event_Checkbox5( lv_event_t * e);
lv_obj_t *ui_Checkbox5;
void ui_event_Checkbox6( lv_event_t * e);
lv_obj_t *ui_Checkbox6;
void ui_event_Checkbox7( lv_event_t * e);
lv_obj_t *ui_Checkbox7;
void ui_event_Checkbox8( lv_event_t * e);
lv_obj_t *ui_Checkbox8;
void ui_event_Checkbox9( lv_event_t * e);
lv_obj_t *ui_Checkbox9;
void ui_event_Checkbox10( lv_event_t * e);
lv_obj_t *ui_Checkbox10;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Label5;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label6;
void ui_event_Label7( lv_event_t * e);
lv_obj_t *ui_Label7;
void ui_event_Label8( lv_event_t * e);
lv_obj_t *ui_Label8;
void ui_event_Checkbox11( lv_event_t * e);
lv_obj_t *ui_Checkbox11;
void ui_event_Checkbox12( lv_event_t * e);
lv_obj_t *ui_Checkbox12;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label9;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Checkbox1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      WaveFormThree( e );
}
}
void ui_event_Checkbox2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      WaveFormTwo( e );
}
}
void ui_event_Checkbox3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      WaveFormOne( e );
}
}
void ui_event_Checkbox4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ChannelOneOn( e );
}
}
void ui_event_Checkbox5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ChannelOneOff( e );
}
}
void ui_event_Checkbox6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      TimeScaleFIVE( e );
}
}
void ui_event_Checkbox7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      TimeScaleFOUR( e );
}
}
void ui_event_Checkbox8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      TimeScaleTHREE( e );
}
}
void ui_event_Checkbox9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      TimeScaleTWO( e );
}
}
void ui_event_Checkbox10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      TimeScaleONE( e );
}
}
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      StopWave( e );
}
}
void ui_event_Label7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ChannelOneVpp( e );
}
}
void ui_event_Label8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ChannelTwoVpp( e );
}
}
void ui_event_Checkbox11( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ChannelTwoOn( e );
}
}
void ui_event_Checkbox12( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ChannelTwoOff( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
