// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Chart1;
extern lv_obj_t *ui_Label1;
void ui_event_Checkbox1( lv_event_t * e);
extern lv_obj_t *ui_Checkbox1;
void ui_event_Checkbox2( lv_event_t * e);
extern lv_obj_t *ui_Checkbox2;
void ui_event_Checkbox3( lv_event_t * e);
extern lv_obj_t *ui_Checkbox3;
void ui_event_Checkbox4( lv_event_t * e);
extern lv_obj_t *ui_Checkbox4;
void ui_event_Checkbox5( lv_event_t * e);
extern lv_obj_t *ui_Checkbox5;
void ui_event_Checkbox6( lv_event_t * e);
extern lv_obj_t *ui_Checkbox6;
void ui_event_Checkbox7( lv_event_t * e);
extern lv_obj_t *ui_Checkbox7;
void ui_event_Checkbox8( lv_event_t * e);
extern lv_obj_t *ui_Checkbox8;
void ui_event_Checkbox9( lv_event_t * e);
extern lv_obj_t *ui_Checkbox9;
void ui_event_Checkbox10( lv_event_t * e);
extern lv_obj_t *ui_Checkbox10;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label6;
void ui_event_Label7( lv_event_t * e);
extern lv_obj_t *ui_Label7;
void ui_event_Label8( lv_event_t * e);
extern lv_obj_t *ui_Label8;
void ui_event_Checkbox11( lv_event_t * e);
extern lv_obj_t *ui_Checkbox11;
void ui_event_Checkbox12( lv_event_t * e);
extern lv_obj_t *ui_Checkbox12;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
