// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void WaveFormThree(lv_event_t * e);
void WaveFormTwo(lv_event_t * e);
void WaveFormOne(lv_event_t * e);
void ChannelOneOn(lv_event_t * e);
void ChannelOneOff(lv_event_t * e);
void TimeScaleFIVE(lv_event_t * e);
void TimeScaleFOUR(lv_event_t * e);
void TimeScaleTHREE(lv_event_t * e);
void TimeScaleTWO(lv_event_t * e);
void TimeScaleONE(lv_event_t * e);
void StopWave(lv_event_t * e);
void ChannelOneVpp(lv_event_t * e);
void ChannelTwoVpp(lv_event_t * e);
void ChannelTwoOn(lv_event_t * e);
void ChannelTwoOff(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
